<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import ToolLayout from '@/components/layout/ToolLayout.vue'
import UiInput from '@/components/ui/UiInput.vue'
import UiTextarea from '@/components/ui/UiTextarea.vue'
import UiAlert from '@/components/ui/UiAlert.vue'
import CopyButton from '@/components/ui/CopyButton.vue'
import { useI18n } from '@/i18n'
import type { ToolMeta } from '@/types/tool'

const route = useRoute()
const tool = route.meta.tool as ToolMeta
const { t } = useI18n()

const syncTaskName = ref('mysql2hive_ods_taobao_sales_inventory_d')
const stripPrefixLen = ref(15)
const primaryKey = ref('id')
const partitionVar = ref('${last_day}')
const fields = ref(`id
sku
skc
insert_time
last_update_time
total_salable_qty`)

const error = ref('')

const fieldList = computed(() =>
  fields.value
    .split('\n')
    .map((l) => l.trim().replace(/[,，]+$/, ''))
    .filter(Boolean),
)

const tableName = computed(() => syncTaskName.value.slice(stripPrefixLen.value))

const sql = computed(() => {
  if (!syncTaskName.value.trim()) {
    error.value = t({ zh: '请输入同步任务名', en: 'Sync task name is required' })
    return ''
  }
  if (!fieldList.value.length) {
    error.value = t({ zh: '请输入字段名', en: 'At least one field is required' })
    return ''
  }
  error.value = ''
  const tn = tableName.value
  const dt = partitionVar.value
  const pk = primaryKey.value || 'id'
  const fields = fieldList.value
  const indent = '  '

  const selectFields = fields.map((f, i) => `${i === 0 ? indent : indent + ','}${f}`).join('\n')
  const mergeSelect = fields
    .map((f, i) => `${i === 0 ? indent : indent + ','}nvl(a.${f}, b.${f}) AS ${f}`)
    .join('\n')

  return `-- ${'='.repeat(76)}
-- Hive 增量合并  ods.ods_${tn}  →  dw.dw_${tn}
-- generated by MyToolBox · do not edit by hand
-- ${'='.repeat(76)}

use dw;
SET hive.execution.engine = mr;

-- 1. Initialize dw table from latest ods snapshot
CREATE TABLE IF NOT EXISTS dw.dw_${tn} AS
SELECT
${selectFields}
FROM ods.ods_${tn}
WHERE dt = '${dt}';

-- 2. Merge incremental data into tmp
CREATE TEMPORARY TABLE dw.tmp_dw_${tn} LIKE dw.dw_${tn};

INSERT OVERWRITE TABLE dw.tmp_dw_${tn}
SELECT
${mergeSelect}
FROM (
  SELECT *
  FROM ods.ods_${tn}
  WHERE dt = '${dt}'
) a
FULL OUTER JOIN dw.dw_${tn} b
  ON a.${pk} = b.${pk};

-- 3. Promote tmp to dw
INSERT OVERWRITE TABLE dw.dw_${tn}
SELECT *
FROM dw.tmp_dw_${tn};

-- ${'='.repeat(76)}`
})
</script>

<template>
  <ToolLayout :tool="tool" variant="wide">
    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
      <div class="space-y-4">
        <div>
          <label class="mb-1.5 block text-sm font-medium text-ink">
            {{ t({ zh: '同步任务名', en: 'Sync task name' }) }}
          </label>
          <UiInput v-model="syncTaskName" mono />
          <p class="mt-1 text-xs text-ink-subtle">
            {{ t({ zh: '示例:', en: 'Example:' }) }} <code class="text-ink-muted">mysql2hive_ods_xxx</code>
          </p>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="mb-1.5 block text-sm font-medium text-ink">
              {{ t({ zh: '前缀截断长度', en: 'Prefix length to strip' }) }}
            </label>
            <UiInput v-model.number="stripPrefixLen" type="number" mono />
          </div>
          <div>
            <label class="mb-1.5 block text-sm font-medium text-ink">
              {{ t({ zh: '主键字段', en: 'Primary key' }) }}
            </label>
            <UiInput v-model="primaryKey" mono />
          </div>
        </div>

        <div>
          <label class="mb-1.5 block text-sm font-medium text-ink">
            {{ t({ zh: '分区变量', en: 'Partition variable' }) }}
          </label>
          <UiInput v-model="partitionVar" mono />
        </div>

        <div>
          <label class="mb-1.5 block text-sm font-medium text-ink">
            {{ t({ zh: '字段列表(每行一个)', en: 'Field list (one per line)' }) }}
          </label>
          <UiTextarea v-model="fields" :rows="12" />
        </div>

        <UiAlert :message="error" />
      </div>

      <div>
        <div class="mb-2 flex items-center justify-between">
          <label class="text-sm font-medium text-ink">{{ t({ zh: '生成的 SQL', en: 'Generated SQL' }) }}</label>
          <CopyButton :text="sql" />
        </div>
        <pre class="max-h-[40rem] overflow-auto rounded-xl border border-border bg-surface-raised p-4 font-mono text-xs leading-relaxed text-ink"><code>{{ sql }}</code></pre>
      </div>
    </div>
  </ToolLayout>
</template>
